# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.TextField(blank=True, null=True)),
                ('uid2', models.TextField(blank=True, null=True)),
                ('time_created', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'FRIENDSHIP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('global_sales', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GAME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(blank=True, null=True)),
                ('gid', models.TextField(blank=True, null=True)),
                ('duration_played', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PLAY_GAME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
    ]
